### ISSUE TITLE
Signup/Login issue

### ISSUE THREAD

**Issue by Nandini80** [Nandini80/CityPlus#17]

**Comment by Adii2202** [comment]
![image](https://github.com/Nandini80/CityPlus/assets/131331573/86bc2f54-eba4-476b-a836-f0900a9aa30c)

**Comment by Hrithikshetty** [comment]
is this sign up/login page is working ..? if not assign me this issue asap...i have already corrected it i just have to push it

**Comment by Gursimranjeet-Singh** [comment]
This issue was fixed earlier in the last pull request which has been merged

**Comment by Hrithikshetty** [comment]
@Gursimranjeet-Singh okay cool...

**Comment by Nandini80** [comment]
@Gursimranjeet-Singh This issue is not fixed. clone the repo again and run. You will face the same issue again.

**Comment by Adii2202** [comment]
i hv done the required changes

**Comment by Adii2202** [comment]
u may  check

**Comment by Gursimranjeet-Singh** [comment]
@Nandini80 works fine for me just now created a codespace on master branch of your remote repo works fine.

**Comment by Nandini80** [comment]
I'm encountering a popup indicating an error with the Axios request.

**Comment by Gursimranjeet-Singh** [comment]
are you following the steps in readme.md that may be occuring because you maybe using old steps for running server.Once can you run by following steps mentioned in readme.md and verify?

**Comment by Nandini80** [comment]
I was running the server and client with npm start and nodemon server and all the other steps were same and I guess there should not be any issue with this thing. Right?

**Comment by Gursimranjeet-Singh** [comment]
no need to run client side  server will render client. just you have to build the client side and then run server .If you want reference  you can refer this https://github.com/Nandini80/CityPlus/pull/12#issuecomment-2006012276
If the issue persist then maybe some issue is there you can then i think review this pull and merge if that suits you.

**Comment by Nandini80** [comment]
@Gursimranjeet-Singh Yes you are right. It's working correctly.Thanks for your contribution. But my only concern is, why is there a need to change the port?
